# Generated by Django 2.0.3 on 2018-04-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('Identificacion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('permiso', models.BooleanField(default=False)),
            ],
        ),
    ]
