# Generated by Django 2.0.3 on 2018-04-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0005_auto_20180408_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='permiso',
            field=models.CharField(choices=[('Tiene permisos de super administrador', '1'), ('No tiene permiso', '0')], default='0', max_length=85),
        ),
    ]
