# Generated by Django 2.0.3 on 2018-04-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0006_auto_20180408_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='permiso',
            field=models.CharField(choices=[('1', 'Tiene permisos de super administrador'), ('0', 'No tiene permiso')], default='0', max_length=85),
        ),
    ]
