# Generated by Django 2.0.3 on 2018-04-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('Nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Ruta', models.CharField(max_length=170)),
                ('Empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.Empresa')),
            ],
        ),
    ]
