# Generated by Django 2.0.3 on 2018-04-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='evaluacioncompetitividad',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='Nombre',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='Contenido',
            field=models.TextField(max_length=500),
        ),
    ]
