# Generated by Django 2.0.3 on 2018-04-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0002_auto_20180410_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='evaluacioncompetitividad',
            name='Nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='Nombre',
            field=models.CharField(max_length=65),
        ),
    ]
