# Generated by Django 2.0.3 on 2018-04-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0004_auto_20180404_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='Tipo_empresa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
